"""update users table

Revision ID: 3da27caba629
Revises: db7f1b66f5c6
Create Date: 2026-06-30 01:55:49.739356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3da27caba629'
down_revision: Union[str, Sequence[str], None] = 'db7f1b66f5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_onboarded', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('account_type', sa.String(), server_default='individual', nullable=False))
    op.add_column('users', sa.Column('academic_level', sa.String(), nullable=True))
    op.add_column('users', sa.Column('institution', sa.String(), nullable=True))
    op.add_column('users', sa.Column('subject_area', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subject_area')
    op.drop_column('users', 'institution')
    op.drop_column('users', 'academic_level')
    op.drop_column('users', 'account_type')
    op.drop_column('users', 'has_onboarded')
    # ### end Alembic commands ###
