"""add created_by to study sessions

Revision ID: a33c8cf206d1
Revises: f7caa2ecdd65
Create Date: 2026-07-16 20:57:57.787609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a33c8cf206d1'
down_revision: Union[str, Sequence[str], None] = 'f7caa2ecdd65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('created_by', sa.String(), nullable=True))
    op.execute("""
    UPDATE sessions 
    SET created_by = user_id 
    WHERE user_id IS NOT NULL
""")
    op.execute("""
        UPDATE sessions 
        SET created_by = groups.created_by 
        FROM groups 
        WHERE sessions.group_id = groups.id AND sessions.created_by IS NULL
    """)
    op.alter_column("sessions", "created_by", nullable=False)

        # Add foreign key
    op.create_foreign_key(
        "fk_sessions_created_by",
        "sessions",
        "users",
        ["created_by"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_sessions_created_by", 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'created_by')
    # ### end Alembic commands ###
