"""remove account type field in User model, and link group and course models with session table

Revision ID: f7caa2ecdd65
Revises: 4fb3dfc23b21
Create Date: 2026-07-10 22:50:47.600726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7caa2ecdd65'
down_revision: Union[str, Sequence[str], None] = '4fb3dfc23b21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('group_id', sa.String(), nullable=True))
    op.add_column('sessions', sa.Column('course_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'sessions', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'sessions', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.drop_column('users', 'account_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('account_type', sa.VARCHAR(), server_default=sa.text("'individual'::character varying"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'course_id')
    op.drop_column('sessions', 'group_id')
    # ### end Alembic commands ###
